export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  FREE_USER = 'ROLE_FREEMIUM_USER',
  PREMIUM_USER = 'ROLE_PREMIUM_USER',
  STANDARD_USER = 'ROLE_STANDARD_USER',
  FREE_PROPRIO = 'ROLE_FREEMIUM_PROPRIO',
  PREMIUM_PROPRIO = 'ROLE_PREMIUM_PROPRIO',
  STANDARD_PROPRIO = 'ROLE_STANDARD_PROPRIO',

}
